In [ ]:

def sum(a,b):
    return a+b

value=sum(2,5)
print(value)






7


In [ ]:
import numpy as np
print(f"Numpy version :{np.__version__}")

Numpy version :2.3.0


In [8]:
arr_1d=np.array([1,2,3,4,5])
arr_1d.ndim
list_2d=[[1,2,3],[4,5,6]]
# print(list[1][0])
arr_2d=np.array(list_2d)

In [10]:
arr_2d[1,2]
print(type(arr_1d))

<class 'numpy.ndarray'>


In [14]:
print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.dtype)
print(arr_2d.ndim)

(2, 3)
6
int64
2


In [16]:
arr=np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
